# Generated by Django 6.0.7 on 2026-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePeer',
            fields=[
                ('peer_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('geohash', models.CharField(db_index=True, max_length=12)),
                ('channel_name', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
